### ISSUE TITLE
cannot allow the app to take pictures

### ISSUE THREAD

**Issue by openmotion** [googlesamples/glass-enterprise-samples#10]
hello
i cannot go with the touchpad to the deny or allow button ( camera permission )
is there a way to do it ?

Is there an android update for the google enterprise 2 ?

thanks

**Comment by jbolinger** [comment]
Hi @openmotion! Yes, the touchpad does work on these dialogs in recent versions. Check the developer site for updates and let us know if you run into trouble: https://developers.google.com/glass-enterprise/downloads/system-images
