### ISSUE TITLE
Default build.Gradle mismatch 

### ISSUE THREAD

**Issue by mikemorrison111** [googlesamples/glass-enterprise-samples#27]
GestureLibrarySample is using Gradle 4.0.1 so sub projects all fail to compile until the Gradle is updated for each of them.  New to Gradle so might have a bad config.

ERROR:
Using multiple versions of the Android Gradle plugin in the same build is not allowed.
	'E:\Glass\glass-enterprise-samples-master\QRCodeScannerSample\app' is using version 4.0.0
	'E:\Glass\glass-enterprise-samples-master\GestureLibrarySample\main' is using version 4.0.1
Open File

------
Windows, Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 24, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 16

**Comment by jbolinger** [comment]
Hey @mikemorrison111 did you change the version to `4.0.1` (I think all our samples are set to `4.0.0`)? Can you check that you didn't make any local changes?

**Comment by mikemorrison111** [comment]
I must have done exactly that somehow. doh!
