### ISSUE TITLE
voicerecognitionsample not working on google glass enterprise 2

### ISSUE THREAD

**Issue by amit-khullar** [googlesamples/glass-enterprise-samples#28]
We have deployed the sample of voice recognition (https://github.com/googlesamples/glass-enterprise-samples/tree/master/VoiceRecognitionSample) on googe glass 2, but its not working, not able to invoke the activity used for voice input and recognition.

Can anyone please suggest a way forward, is there any extra dependency required to be installed for this sample to work on glass, we have been stuck for quite some time and its really urgent.

**Comment by jbolinger** [comment]
What version of the OS are you using? Try updating [here](https://developers.google.com/glass-enterprise/downloads/system-images) if it's not recent. Voice recognition is not included in older versions of the OS.

**Comment by jbolinger** [comment]
Closing since we haven't heard back. Feel free to reopen if this is still an issue.
