### ISSUE TITLE
May I use these samples with Glass Explorer Edition?

### ISSUE THREAD

**Issue by minakhan01** [googlesamples/glass-enterprise-samples#33]
I know that you've system images here: https://developers.google.com/glass-enterprise/downloads/system-images and EE1 to EE2 update instructions here: https://developers.google.com/glass-enterprise/guides/get-started. Would it be okay/possible for me to update my explorer version to the new system images?

I'm also aware of the different specifications: 
![image](https://user-images.githubusercontent.com/6627535/103981231-698c4a00-514f-11eb-9147-9d0c24c863f8.png)

I have also successfully followed the instructions here: https://support.google.com/glass/answer/9649198?hl=en. Thank you :)

**Comment by jbolinger** [comment]
Hi @minakhan01, sorry but the explorer and enterprise products are different and using the newer system images for EE2 will not work. Similarly, these samples are intended for EE2 developers, but let us know if you are looking for anything specific and we might be able to help.
