### ISSUE TITLE
Camera2Sample

### ISSUE THREAD

**Issue by openmotion** [googlesamples/glass-enterprise-samples#8]
hello
how can i allow the app to access photos, media and file on the device, because i cannot scroll, and confirm the "allow" button
so i cannot use the app
thanks

**Comment by openmotion** [comment]
i found a workaround with adb, simulating input :
adb shell input tap 413 251
(pos X and Y of the button allow)

**Comment by jbolinger** [comment]
That will work. These dialogs are usable with the touchpad on recent versions of the OS so you may want to update if you haven't done so in awhile.
